workflows:
  my-workflow:
    scripts:
      - name: test
        script: |
          npx envinfo
          yarn
          cd ios
          export LC_ALL=en_US.UTF-8
          pod install
          cd ..
          xcodebuild ONLY_ACTIVE_ARCH=YES -workspace ios/MyApp.xcworkspace -scheme MyApp -configuration Release -sdk iphonesimulator -derivedDataPath ios/build -UseModernBuildSystem=YES
          mkdir Payload && cp -r ios/build/Build/Products/Release-iphonesimulator/MyApp.app Payload/
          zip -r Payload.zip Payload && mv Payload.zip MyApp.ipa
          cp Payload.zip $BITRISE_DEPLOY_DIR
    artifacts:
      - MyApp.ipa

