name: iOS Staging

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      message:
        description: 'Build description'

jobs:
  build:
    runs-on: macOS-latest

    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: |
          yarn install
          cd ios
          export LC_ALL=en_US.UTF-8
          pod install
          cd ../

      - name: Lint & test
        run: |
          yarn install
          yarn run lint
          yarn test

      - name: Bundle install
        run: |
          xcodebuild ONLY_ACTIVE_ARCH=YES -workspace ios/MyApp.xcworkspace -scheme MyApp -configuration Release -sdk iphonesimulator -derivedDataPath ios/build -UseModernBuildSystem=YES
          mkdir Payload && cp -r ios/build/Build/Products/Release-iphonesimulator/MyApp.app Payload/
          zip -r Payload.zip Payload && mv Payload.zip MyApp.ipa
